/* --- the wiki cannot drift from the game ---------------------------------

   tools/wiki.cpp generates web/wiki/ from the game's own tables, and WIKI.md
   claims on that basis that the wiki "cannot drift from the game". This file is
   what makes that claim true rather than merely plausible.

   It matters more here than it would for a wiki generated in CI, because this
   one is regenerated BY HAND. `scripts/run_wiki.sh` runs when you say so, and
   the output is committed -- so between a change to the game and the next run
   of that script, the published site is wrong. Nothing else would notice.

   So this test reads the COMMITTED OUTPUT off disk and checks it against the
   live tables. A material added, an item renamed, a recipe retuned: the pages
   stop matching, and the suite says so with the one-line fix. It is the staleness
   alarm as much as it is a correctness check, which is why a failure here reads
   "run scripts/run_wiki.sh" rather than "the generator is broken".

   What is checked:

     every material, item, creature and device has a page   (nothing missing)
     every page corresponds to something real               (nothing left over)
     every recipe's inputs and output resolve               (no dangling ids)
     every internal link lands on a file that exists        (no dead ends)
     every page is whole -- header, main, closing html      (nothing truncated)
     one icon class per stackable item, and a sheet to match

   Compile with every src cpp except main.cpp. Note it runs from build/tbin, so
   it finds the repository root by walking up rather than assuming a cwd -- the
   thing that made flower_seeds pass by hand and fail under the runner. */

#include "materials.h"
#include "item.h"
#include "craft.h"
#include "entity.h"
#include "device.h"
#include "sprite.h"
#include "multiplayer.h"

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <string>
#include <vector>
#include <set>

static int failures = 0;
static void check(bool ok, const char* what) {
    printf("  %-62s %s\n", what, ok ? "ok" : "FAIL");
    if (!ok) ++failures;
}

/* --- finding the wiki ----------------------------------------------------
   The harness runs from build/tbin, not the repository root. Walk up until
   src/materials.h is found rather than hard-coding "../../", so the test
   behaves the same run by hand and run by the suite. */
static std::string g_root;

static bool fileExists(const std::string& path) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return false;
    fclose(f);
    return true;
}

static bool findRoot() {
    std::string prefix;
    for (int up = 0; up < 6; ++up) {
        if (fileExists(prefix + "src/materials.h")) { g_root = prefix; return true; }
        prefix += "../";
    }
    return false;
}

static std::string wikiPath(const std::string& relative) {
    return g_root + "web/wiki/" + relative;
}

static std::string readFile(const std::string& path) {
    FILE* f = fopen(path.c_str(), "rb");
    if (!f) return std::string();
    fseek(f, 0, SEEK_END);
    long len = ftell(f);
    fseek(f, 0, SEEK_SET);
    std::string out((size_t)(len > 0 ? len : 0), '\0');
    if (len > 0) {
        size_t got = fread(&out[0], 1, (size_t)len, f);
        out.resize(got);
    }
    fclose(f);
    return out;
}

/* Must match slugify() in tools/wiki.cpp. Two copies of a rule is normally the
   problem rather than the check -- but here that is the point: if the generator
   changes how it names a file and this does not, every page "goes missing" and
   the test says so loudly. A shared header would let both drift together. */
static std::string slugify(const char* name) {
    std::string out;
    bool lastHyphen = true;
    for (const char* p = name; *p; ++p) {
        char c = *p;
        if (c >= 'A' && c <= 'Z') c = (char)(c - 'A' + 'a');
        const bool alnum = (c >= 'a' && c <= 'z') || (c >= '0' && c <= '9');
        if (alnum) { out += c; lastHyphen = false; }
        else if (!lastHyphen) { out += '-'; lastHyphen = true; }
    }
    while (!out.empty() && out[out.size() - 1] == '-') out.erase(out.size() - 1);
    return out;
}

/* Every page the generator should have written, collected so both directions
   can be checked: nothing missing, and nothing left over. */
struct Expected {
    std::string path;     /* relative to web/wiki/ */
    std::string what;     /* for the failure message */
};

int main() {
    initMaterials();
    initItems();
    initSprites();
    playerSessionsReset();

    if (!findRoot()) {
        fprintf(stderr, "cannot find the repository root from here\n");
        return 2;
    }
    if (!fileExists(wikiPath("index.html"))) {
        fprintf(stderr,
                "web/wiki/ is not generated. Run:  bash scripts/run_wiki.sh\n");
        return 2;
    }

    std::vector<Expected> expected;
    expected.push_back((Expected){ "index.html", "the hub" });
    expected.push_back((Expected){ "materials/index.html", "the material index" });
    expected.push_back((Expected){ "items/index.html", "the item index" });
    expected.push_back((Expected){ "recipes/index.html", "the recipe index" });
    expected.push_back((Expected){ "creatures/index.html", "the creature index" });
    expected.push_back((Expected){ "devices/index.html", "the device index" });
    expected.push_back((Expected){ "guide/index.html", "the guide index" });

    for (int i = 1; i < MAT_COUNT; ++i)
        expected.push_back((Expected){ "materials/" + slugify(MATS[i].name) + ".html",
                                       MATS[i].name });
    for (int i = MAT_COUNT; i < ITEM_COUNT; ++i)
        if (ITEMS[i].maxStack)
            expected.push_back((Expected){ "items/" + slugify(ITEMS[i].name) + ".html",
                                           ITEMS[i].name });
    for (int t = 1; t < ENT_COUNT; ++t)
        expected.push_back((Expected){ "creatures/" + slugify(ENT_DEFS[t].name) + ".html",
                                       ENT_DEFS[t].name });
    for (int d = 1; d < DEV_COUNT; ++d)
        expected.push_back((Expected){ "devices/" + slugify(DEVS[d].name) + ".html",
                                       DEVS[d].name });
    for (int st = 0; st < STATION_COUNT; ++st)
        expected.push_back((Expected){ "recipes/" + slugify(STATION_NAMES[st]) + ".html",
                                       STATION_NAMES[st] });

    printf("checking %d expected pages under web/wiki/\n", (int)expected.size());

    /* --- nothing the game has is missing from the site ------------------ */
    {
        int missing = 0;
        for (size_t i = 0; i < expected.size(); ++i) {
            if (fileExists(wikiPath(expected[i].path))) continue;
            if (missing < 8)
                printf("  no page for %s (%s)\n",
                       expected[i].what.c_str(), expected[i].path.c_str());
            ++missing;
        }
        if (missing)
            printf("  %d page(s) missing -- run: bash scripts/run_wiki.sh\n", missing);
        check(missing == 0, "every material, item, creature and device has a page");
    }

    /* --- and every page is whole ---------------------------------------- */
    {
        int broken = 0;
        for (size_t i = 0; i < expected.size(); ++i) {
            const std::string body = readFile(wikiPath(expected[i].path));
            if (body.empty()) { ++broken; continue; }
            /* A page cut off mid-write still opens in a browser and looks
               almost right, which is the failure worth catching: the closing
               tag is the only thing that proves the generator finished. */
            const bool whole = body.find("<main>") != std::string::npos &&
                               body.find("</main>") != std::string::npos &&
                               body.find("</html>") != std::string::npos &&
                               body.size() > 400;
            if (!whole) {
                if (broken < 5)
                    printf("  %s is empty or truncated (%d bytes)\n",
                           expected[i].path.c_str(), (int)body.size());
                ++broken;
            }
        }
        check(broken == 0, "and none of them is empty or cut off");
    }

    /* --- every recipe points at something real -------------------------- */
    {
        int bad = 0;
        for (int r = 0; r < N_RECIPES; ++r) {
            const Recipe& rec = RECIPES[r];
            if (rec.out == ITEM_NONE || rec.out >= ITEM_COUNT ||
                !ITEMS[rec.out].name || !ITEMS[rec.out].name[0]) {
                printf("  recipe %d makes an item that does not exist\n", r);
                ++bad;
                continue;
            }
            for (int k = 0; k < CRAFT_MAX_IN; ++k) {
                if (!rec.in[k].item) continue;
                if (rec.in[k].item >= ITEM_COUNT ||
                    !ITEMS[rec.in[k].item].name || !ITEMS[rec.in[k].item].name[0]) {
                    printf("  recipe for %s needs an item that does not exist\n",
                           ITEMS[rec.out].name);
                    ++bad;
                }
            }
        }
        check(bad == 0, "every recipe's inputs and output are real items");
    }

    /* --- every recipe reached a station page ---------------------------- */
    {
        int placed = 0;
        for (int st = 0; st < STATION_COUNT; ++st) {
            const std::string page =
                readFile(wikiPath("recipes/" + slugify(STATION_NAMES[st]) + ".html"));
            size_t at = 0;
            while ((at = page.find("<tr><td>", at)) != std::string::npos) {
                ++placed;
                at += 8;
            }
        }
        if (placed != N_RECIPES)
            printf("  %d recipe rows on the station pages, %d in the table\n",
                   placed, N_RECIPES);
        check(placed == N_RECIPES, "and every one of them appears on a station page");
    }

    /* --- one icon per stackable item ------------------------------------ */
    {
        const std::string css = readFile(wikiPath("icons.css"));
        int wanted = 0, found = 0;
        for (int i = 1; i < ITEM_COUNT; ++i) {
            if (!ITEMS[i].maxStack) continue;
            ++wanted;
            char needle[32];
            snprintf(needle, sizeof(needle), ".i%d {", i);
            if (css.find(needle) != std::string::npos) ++found;
        }
        check(fileExists(wikiPath("icons.png")), "the icon sheet exists");
        if (found != wanted)
            printf("  %d icon classes for %d stackable items\n", found, wanted);
        check(found == wanted, "and every stackable item has a cell in it");
    }

    /* --- every internal link lands somewhere ---------------------------- */
    {
        int checked = 0, dead = 0;
        for (size_t i = 0; i < expected.size(); ++i) {
            const std::string page = readFile(wikiPath(expected[i].path));
            /* The directory this page sits in, for resolving relative hrefs. */
            std::string dir = expected[i].path;
            const size_t slash = dir.rfind('/');
            dir = (slash == std::string::npos) ? std::string() : dir.substr(0, slash + 1);

            static const char* ATTRS[] = { "href=\"", "src=\"" };
            for (int a = 0; a < 2; ++a) {
                size_t at = 0;
                const size_t alen = strlen(ATTRS[a]);
                while ((at = page.find(ATTRS[a], at)) != std::string::npos) {
                    at += alen;
                    const size_t end = page.find('"', at);
                    if (end == std::string::npos) break;
                    std::string href = page.substr(at, end - at);
                    at = end;
                    if (href.empty()) continue;
                    if (href.compare(0, 4, "http") == 0) continue;
                    if (href[0] == '#' || href[0] == '/') continue;

                    /* Resolve ../ by hand; the paths here are shallow. */
                    std::string full = dir + href;
                    size_t up;
                    while ((up = full.find("../")) != std::string::npos) {
                        if (up == 0) { full = full.substr(3); continue; }
                        size_t prev = full.rfind('/', up - 2);
                        full = (prev == std::string::npos)
                             ? full.substr(up + 3)
                             : full.substr(0, prev + 1) + full.substr(up + 3);
                    }
                    ++checked;
                    /* A link out of the wiki (the game page, the favicon)
                       resolves against web/ instead. */
                    if (!fileExists(wikiPath(full)) &&
                        !fileExists(g_root + "web/" + full)) {
                        if (dead < 8)
                            printf("  %s links to %s, which is not there\n",
                                   expected[i].path.c_str(), href.c_str());
                        ++dead;
                    }
                }
            }
        }
        printf("  %d internal links checked\n", checked);
        check(checked > 1000, "there are links to check");
        check(dead == 0, "and every one of them lands on a file that exists");
    }

    /* --- can a reader actually get there? -------------------------------

       A page that exists and that nothing links to is not on the site in any
       sense a reader cares about. Every earlier check asks whether pages exist
       and whether links work; this one walks the site the way a person does,
       from the hub outward, and asks how far away the furthest page is.

       Reported as a NUMBER rather than a pass/fail, so a regression shows up as
       the depth creeping from 2 to 4 rather than as a check that silently
       still passes. The cap is three clicks: hub, index, page. Anything past
       that means a section has grown a layer nobody planned. */
    {
        std::set<std::string> seen;
        std::vector<std::string> frontier;
        std::vector<std::string> next;
        frontier.push_back("index.html");
        seen.insert("index.html");

        int depth = 0, deepest = 0;
        while (!frontier.empty() && depth < 12) {
            next.clear();
            for (size_t i = 0; i < frontier.size(); ++i) {
                const std::string here = frontier[i];
                const std::string page = readFile(wikiPath(here));
                std::string dir = here;
                const size_t slash = dir.rfind('/');
                dir = (slash == std::string::npos) ? std::string()
                                                   : dir.substr(0, slash + 1);
                size_t at = 0;
                while ((at = page.find("href=\"", at)) != std::string::npos) {
                    at += 6;
                    const size_t end = page.find('"', at);
                    if (end == std::string::npos) break;
                    std::string href = page.substr(at, end - at);
                    at = end;
                    if (href.empty() || href[0] == '#' || href[0] == '/') continue;
                    if (href.compare(0, 4, "http") == 0) continue;
                    if (href.size() < 5 ||
                        href.compare(href.size() - 5, 5, ".html") != 0) continue;

                    std::string full = dir + href;
                    size_t up;
                    while ((up = full.find("../")) != std::string::npos) {
                        if (up == 0) { full = full.substr(3); continue; }
                        size_t prev = full.rfind('/', up - 2);
                        full = (prev == std::string::npos)
                             ? full.substr(up + 3)
                             : full.substr(0, prev + 1) + full.substr(up + 3);
                    }
                    /* Links that climb out of web/wiki (the game page) are not
                       part of the wiki's own graph. */
                    if (!fileExists(wikiPath(full))) continue;
                    if (seen.count(full)) continue;
                    seen.insert(full);
                    next.push_back(full);
                }
            }
            if (!next.empty()) { ++depth; deepest = depth; }
            frontier = next;
        }

        int unreachable = 0;
        for (size_t i = 0; i < expected.size(); ++i) {
            if (seen.count(expected[i].path)) continue;
            if (unreachable < 8)
                printf("  nothing links to %s (%s)\n",
                       expected[i].what.c_str(), expected[i].path.c_str());
            ++unreachable;
        }
        printf("  %d pages reachable from the hub, furthest is %d click(s) away\n",
               (int)seen.size(), deepest);
        check(unreachable == 0, "every page can be reached from the hub");
        check(deepest <= 3, "and none of them is more than three clicks away");
    }

    /* --- the prose pages were rendered ---------------------------------- */
    {
        /* Named here rather than read from the generator, so removing a page
           from PROSE[] without meaning to is caught. */
        const std::string circuits = readFile(wikiPath("guide/circuits.html"));
        check(circuits.find("Circuit Wire") != std::string::npos,
              "the circuits guide rendered its source");
        check(circuits.find("## ") == std::string::npos,
              "and no markdown was left unrendered");
    }

    /* --- the pages agree with the tables about what things are called ---- */
    {
        /* The cheapest possible drift test, and the one most likely to fire:
           a renamed material whose page was never regenerated still sits there
           under its old name. */
        int wrong = 0;
        for (int i = 1; i < MAT_COUNT; ++i) {
            const std::string page =
                readFile(wikiPath("materials/" + slugify(MATS[i].name) + ".html"));
            if (page.empty()) continue;
            if (page.find(MATS[i].name) == std::string::npos) {
                if (wrong < 5)
                    printf("  the page for %s does not name it\n", MATS[i].name);
                ++wrong;
            }
        }
        check(wrong == 0, "every material page names its own material");
    }

    /* --- the authored exception list is still real ----------------------
       tools/wiki.cpp carries a short list of relationships that live in
       world.cpp rather than in a table -- the fuel-to-coke chain above all.
       Being authored, it is the one part of the generator that CAN rot: ids
       renumber, materials get renamed. Checked by name so that it does. */
    {
        const std::string fuel = readFile(wikiPath("materials/fuel.html"));
        const std::string coke = readFile(wikiPath("materials/coke.html"));
        check(fuel.find("coke.html") != std::string::npos,
              "fuel links to coke, which no table says it becomes");
        check(coke.find("coke-ember.html") != std::string::npos,
              "and coke links on to coke ember");
    }

    if (failures) {
        fprintf(stderr,
                "\n%d wiki check(s) failed.\n"
                "If the game changed and the wiki did not, the fix is:\n"
                "    bash scripts/run_wiki.sh\n", failures);
        return 1;
    }
    printf("\nthe wiki matches the game\n");
    return 0;
}
