"""Regenerate src/audio_embedded.h from every registered sound.

Run after changing sounds: python tools/embed_sfx.py
The game prefers loose res/sfx WAVs while developing; this fallback keeps a
standalone Windows executable (including launcher downloads) audible too.
"""
from pathlib import Path
import re

ROOT = Path(__file__).resolve().parents[1]
NAMES = re.findall(
    r'X\(SFX_[A-Z_]+,\s*"([^"]+\.wav)"',
    (ROOT / "src" / "audio.h").read_text(encoding="utf-8"),
)
if len(NAMES) < 100:
    raise ValueError("cue registry parse failed")

lines = [
    "// Generated by tools/embed_sfx.py. Do not edit by hand.",
    "#pragma once",
    "struct EmbeddedSfx { const unsigned char* data; unsigned size; };",
]
for index, name in enumerate(NAMES):
    payload = (ROOT / "res" / "sfx" / name).read_bytes()
    lines.append(f"static const unsigned char embeddedSfx{index}[] = {{")
    for start in range(0, len(payload), 24):
        lines.append("    " + ", ".join(f"0x{b:02x}" for b in payload[start:start + 24]) + ",")
    lines.append("};")
lines.append("static const EmbeddedSfx EMBEDDED_SFX[] = {")
for index, _ in enumerate(NAMES):
    lines.append(f"    {{ embeddedSfx{index}, sizeof(embeddedSfx{index}) }},")
lines += ["};", f"static const int EMBEDDED_SFX_COUNT = {len(NAMES)};", ""]
(ROOT / "src" / "audio_embedded.h").write_text("\n".join(lines), encoding="ascii")
